
[env]
TERM = "xterm-256color"

[font]
size = 11

[font.bold]
family = "FiraCode Nerd Font Mono"
style = "Bold"

[font.bold_italic]
family = "FiraCode Nerd Font Mono"
style = "Bold Italic"

[font.italic]
family = "FiraCode Nerd Font Mono"
style = "Italic"

[font.normal]
family = "FiraCode Nerd Font Mono"
style = "Regular"

[window]
opacity = 0.5

[window.padding]
x = 2
y = 2

[general]
live_config_reload = true
import = ["/home/tom/.config/alacritty/dracula.toml"]
